baseURL = "https://netlify-photo-gallery.netlify.com/"
languageCode = "en-us"
title = "Netlify photo gallery"

[menu]
  [[menu.main]]
    identifier = "top"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "photos_m"
    name = "Photo gallery (masonry)"
    url = "/photos_m/"
  [[menu.main]]
    identifier = "photos_s"
    name = "Photo gallery (square)"
    url = "/photos_s/"
